### ISSUE TITLE
Return code fields inconsistent

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#10]
##### SUMMARY
The fields used to convey return codes are different in the various modules. They should be using more consistent naming perhaps ?

`changed` is consistent it seems. Good.
`rc`, `ret_code` and `api_response` or `failed` seem to be doing similar things...

eg: 
cmci module: 
This module seems pretty inconsistent with the others. I guess it's more complex, but we should 
- failed True if query_job failed, othewise False. 
  - >> Why specifically call this out for the query job ?
-  url 
  - >> I don't really understand why this is returned.
- api_response
- response

dfhccutl:
- msg
- rc
- content 

dfhcsdup:
- ret_code
- cmds
- content

dfhrmutl:
- msg
- rc
- content

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
all the modules.

##### ANSIBLE VERSION
n/a

**Comment by techcobweb** [comment]
In the zOS core modules, I also see a mixture of `ret_code` , `rc`, `code`, `msg_code ` ...etc. 
So that can't really be used as guidance for consistency either really.

**Comment by stewartfrancis** [comment]
CMCI module return codes are consistent with CMCI API field names now
