### ISSUE TITLE
Oddness in doc explanation of required username and password

### ISSUE THREAD

**Issue by ind1go** [ansible-collections/ibm_zos_cics#107]
##### SUMMARY

In a few places in the doc there are this kind of problem:

![if cmci_user and (cmci_password)](https://user-images.githubusercontent.com/1038350/145074379-de2b045b-eba9-4c4f-a48e-b21ec9b03fb1.png)

I think the intention is that the password is in italics.

**Comment by vera-chan** [comment]
I can take a look at this.
