### ISSUE TITLE
Inconsistent naming of csd fields.

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#11]
##### SUMMARY
Inconsistent naming of csd fields.

Input field `dfhcsd` - Specifies the CSD file which you read from or write to.
And yet the output field is called `csd` - The CSD data set used.

>> Can the input field please be called `csd`. Why do we need the `dfh` prefix ? I don't think we do.

We also have the input field `seccsd` - Specifies the CSD file which you read from or write to.
>> Why do we need a separate field for another CSD file ?
>> perhaps calling it `csd_2` or `target_csd` as opposed to `source_csd` or something to make it distinct, or re-use the other csd-type field (currently called `dfhcsd`)...
 
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cics_dfhcsdup  docs page.

##### ANSIBLE VERSION
n/a

**Comment by stewartfrancis** [comment]
We're not shipping the dfhcsd module currently, so closing this for now
