### ISSUE TITLE
Update links to CICS TS documentation to target latest release

### ISSUE THREAD

**Issue by markcocker** [ansible-collections/ibm_zos_cics#113]
##### SUMMARY
1. Links to CICS TS documentation current target CICS TS 5.6. Ideally they should target the latest release using `latest` in the URL instead of the release number.
2. The URL has changed from the IBM Knowledge Center format to the IBM Documentation format.
3. `/en/` is not consistently included in the URLs.

Search for `https://www.ibm.com/support/knowledgecenter/` to see the URLs that need updating.

For example change:

```text
https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.6.0/reference-cpsm-restables/cpsm-restables/PROGRAMtab.html
```

to:

```text
https://www.ibm.com/docs/en/cics-ts/latest?topic=tables-program-resource-table
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cmci.py
cmci_action.rst
cmci_create.rst
cmci_delete.rst
cmci_get.rst
cmci_update.rst

##### ANSIBLE VERSION
```
5.13.2
```

**Comment by stewartfrancis** [comment]
@ddimatos Could you rebuild the documentation on the integrated doc site from our main branch when you get a chance please?

**Comment by ddimatos** [comment]
@stewartfrancis sure, we are doing it likely tomorrow for zosmf as well

**Comment by stewartfrancis** [comment]
Thanks, I'll close this assuming that all goes smoothly

**Comment by ddimatos** [comment]
Should be done today, was waiting to pair it with zosmf update, anyhow, registry changes are done to pull the doc you should check back later today and make sure your updates are as you expect. What the 

Keep an eye on https://github.com/IBM/z_ansible_collections_doc/tree/gh-pages @itsBryantP helping out and going to generate doc.

**Comment by itsBryantP** [comment]
The doc site has been refreshed, please do check that all the URL changes are resolving appropriately.

**Comment by markcocker** [comment]
This page has been updated:
https://ibm.github.io/z_ansible_collections_doc/ibm_zos_cics/docs/ansible_content.html

but sub-pages to https://ibm.github.io/z_ansible_collections_doc/ibm_zos_cics/docs/source/modules.html have not updated yet.

**Comment by markcocker** [comment]
@itsBryantP can you re-open this issue as the to sub-pages to https://ibm.github.io/z_ansible_collections_doc/ibm_zos_cics/docs/source/modules.html have not updated.
