### ISSUE TITLE
.rst files not in sync with their source

### ISSUE THREAD

**Issue by markcocker** [ansible-collections/ibm_zos_cics#124]
The ibm_zos_cics generated documentation module files, for example
https://github.com/ansible-collections/ibm_zos_cics/blob/main/docs/source/modules/cmci_action.rst
is not in sync with the latest changes in 
https://github.com/ansible-collections/ibm_zos_cics/blob/main/plugins/modules/cmci_action.py
for example it contains URL path to 
`https://www.ibm.com/support/knowledgecenter/SSGMCP_5.6.0/`
rather than
`https://www.ibm.com/docs/en/cics-ts/latest`

I don't see any dev branches to check.

##### SUMMARY

As above, the generated .rst files not not in sync with the source files.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

cmci_action.rst

##### ANSIBLE VERSION

```paste below
N/A
```

**Comment by andrewhughes101** [comment]
The rst's are now in sync with the python source files now, so going to close this
