### ISSUE TITLE
Python install instructions should not call out x86 machines explicitly.

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#2]
Not reported before.
Affects latest branch.

##### SUMMARY

In the python install instructions, I see 
```Download the binaries, installation files, and the README.ZOS onto an x86 machine.```
… why call out `x86` machines specifically ? What about power machines, or an ARM-based raspberri pi, or equivalent. We shouldn’t care about the type of machine people download to, so long as they can upload the contents from there onto zOS ? 

Perhaps a “desktop/client machine” or something might be better than calling out x86 architecture.

PX>
Well，actually this part is pretty similar as the ibm_z_core collection and ibm_z_ims collection,  looks like x86 here actually a requirement of install ansible.

MC>
This is in the section about installing python on zos, not installing ansible.

PX>
oh, yes you are right, that’s not accurate， according to latest announcement of  ibm python, this page might need updated according to https://ansible-collections.github.io/ibm_zos_core/requirements.html

PX>
Thanks for spotting this

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ibm_zos_cics/requirements.html

##### ANSIBLE VERSION
```
n/a
```

**Comment by stewartfrancis** [comment]
We don't include instructions about installing Python on z/OS in our repo anymore, and link to more appropriate places
