### ISSUE TITLE
Python level for cics modules differs from the zOS modules = bad for users ?

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#3]
##### SUMMARY

I notice that the cics modules recommend a rocket python 2.7 or higher to be installed on the managed nodes. Shouldn’t the requirements of the managed nodes match that of the zos core modules ? They are recommending IBM Open Enterprise Python for z/OS. Certainly customers are not going to want to install 2 levels of python so the machine can be manipulated by both modules no ? 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
requirements doc

##### ANSIBLE VERSION
n/a

**Comment by stewartfrancis** [comment]
We'll be supporting python 2.7 plus, as we don't have a requirement to run on z/OS for the CMCI module.  We will be requiring IBM Open Enterprise Python 3.8 when running on z/OS, which is documented
