### ISSUE TITLE
zOS levels differ between cics and zos core modules.

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#4]
##### SUMMARY
I get that the required zOS level for managed nodes is different from Cics modules (V02.02.00) when compared to the zos core modules (V2R3+). In that if you want to mix and match commands between CICS modules and zOS core modules, you are going to have to have the V2R3 or above version installed on the managed nodes. Wondering if
(a) they should be the same for simplicity,
(b) they should both use the same VxRy notation, rather than Vnn.nn.nn

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
The requirements section of the doc

##### ANSIBLE VERSION
n/a

**Comment by stewartfrancis** [comment]
Our modules no-longer have a z/OS pre-req, as they can be executed off-platform
