### ISSUE TITLE
Commented-out unit tests should either pass or be deleted.

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#6]
##### SUMMARY
Unit tests commented out should either be made to work or deleted.
Shipping unit tests commented-out either highlights something which doesn't currently work, which should, or the test is invalid. 
eg: [test_cics_dfhcsdup_func.py](https://github.com/ansible-collections/ibm_zos_cics/blob/feature/1236/cics_dfhcsdup/tests/functional/modules/test_cics_dfhcsdup_func.py)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cics_dfhcsdup

##### ANSIBLE VERSION
n/a

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS
n/a

**Comment by stewartfrancis** [comment]
We're not shipping dfhcsd, so these tests have been deleted, but all the remaining tests are uncommented and pass
