### ISSUE TITLE
security_type attribute in module definition

### ISSUE THREAD

**Issue by techcobweb** [ansible-collections/ibm_zos_cics#7]
##### SUMMARY
 Security type is documented as this:
```
security_type
the authenticate type that remote region requires

required: True
type: str
default: none
choices: none, basic, certificate
but when we document the cmci_user parameter, we have this:
cmci_user
The user id to run the CMCI request with.

Required when security type is yes.
```

yes in the last part isn’t a valid value for security type.
Not sure what it should be. Can you correct please ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
module doc

##### ANSIBLE VERSION
n/a

**Comment by stewartfrancis** [comment]
Pulled security type now, in favour of the users specifying the http scheme they'd like to use: http or https
